### ISSUE TITLE
Test Failures Causing Builds to Fail

### ISSUE THREAD

**Issue by emoshaya-cognito** [web-automation/bootstraped-multi-test-results-report#8]
Not an issue per se, but an improvement request. After experimenting with this plugin, we found that the plugin was marking build as failures when their were test failures. What we would really love is to have an option to not fail the builds but mark them as unstable. Similar to https://github.com/jenkinsci/cucumber-reports-plugin which has a check box ("Ignore failed tests" Tick this if you don't want the entire build to fail when these tests fail. If so, build become unstable) 

In the meantime, I had to disable the use of this plugin due its nature of failing builds....

Much Appreciated!

**Comment by BogdanLivadariu** [comment]
@emoshaya-cognito will do

**Comment by BogdanLivadariu** [comment]
@emoshaya-cognito  [this](https://github.com/BogdanLivadariu/bootstraped-multi-test-results-report/commit/85e71c8ff15688ed166ef2cfc1de2e362da1e839) should cover the feature you've requested


I will add the same support for the rest of the modules, and will release 1.4.6 on monday morning ;)

**Comment by emoshaya-cognito** [comment]
absolutely fantastic! thank you very much for your time on this!

**Comment by emoshaya-cognito** [comment]
Hi @BogdanLivadariu I updated the plugin just now and the builds are unstable now when there are test failures. However, I've noticed the pie charts are missing in the cucumber report.. Please see screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/8818542/11796345/bc82d396-a2b3-11e5-93c1-000f844496ee.jpg)

**Comment by BogdanLivadariu** [comment]
@emoshaya-cognito can you send me the reports for which the charts are not being displayed ?

**Comment by emoshaya-cognito** [comment]
[cucumber_json.txt](https://github.com/BogdanLivadariu/bootstraped-multi-test-results-report/files/62635/cucumber_json.txt)

**Comment by BogdanLivadariu** [comment]
Hm... Can you open the browser console an hit refresh on the report, and see if there are errors there ?

**Comment by emoshaya-cognito** [comment]
Mixed Content: The page at 'https://jenkins.service.com/InventoryItemServices-CucumberTests/166/cucumber-reports-with-handlebars/' was loaded over HTTPS, but requested an insecure script 'http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js'. This request has been blocked; the content must be served over HTTPS.
bootstrap.min.js:6 Uncaught Error: Bootstrap's JavaScript requires jQuery
jenkins.cognitoservice.com/:1 Mixed Content: The page at 'https://jenkins.service.com/view/Deployment%20Dashboard/job/CognitoI…/InventoryItemServices-CucumberTests/166/cucumber-reports-with-handlebars/' was loaded over HTTPS, but requested an insecure script 'http://code.highcharts.com/highcharts.js'. This request has been blocked; the content must be served over HTTPS.
jenkins.cognitoservice.com/:1 Mixed Content: The page at 'https://jenkins.service.com/view/Deployment%20Dashboard/job/CognitoI…/InventoryItemServices-CucumberTests/166/cucumber-reports-with-handlebars/' was loaded over HTTPS, but requested an insecure script 'http://code.highcharts.com/highcharts-3d.js'. This request has been blocked; the content must be served over HTTPS.
jenkins.cognitoservice.com/:1 Mixed Content: The page at 'https://jenkins.service.com/view/Deployment%20Dashboard/job/CognitoI…/InventoryItemServices-CucumberTests/166/cucumber-reports-with-handlebars/' was loaded over HTTPS, but requested an insecure script 'http://code.highcharts.com/modules/exporting.js'. This request has been blocked; the content must be served over HTTPS.
bootstrap-toggle.min.js:8 Uncaught ReferenceError: jQuery is not defined
jenkins.cognitoservice.com/:97 Uncaught ReferenceError: $ is not defined
jenkins.cognitoservice.com/:363 Uncaught ReferenceError: $ is not defined
jenkins.cognitoservice.com/:461 Uncaught ReferenceError: jQuery is not defined

**Comment by BogdanLivadariu** [comment]
@emoshaya-cognito looks like I will need to change the way I load resources for the report.

this is covered by #6 , hope will implement it in the following days, and release a new version.

**Comment by BogdanLivadariu** [comment]
closing this as it will be covered by #6
